### ISSUE TITLE
Bug: Many Services missing (/usr/lib/systemd/system and /lib/systemd/system)

### ISSUE THREAD

**Issue by theofficialgman** [hakandundar34coding/system-monitoring-center#101]
I have one services located in `/usr/lib/systemd/system` and hundreds of services in `/lib/systemd/system`

because of this, only the one service shows. both folders should be checked for services

**Comment by hakandundar34coding** [comment]
How many services are listed in v1.22.0?

**Comment by theofficialgman** [comment]
its the same in all previous versions. I added a application that adds its service in /usr/lib/systemd/system where all other services are in /lib/systemd/system and now only the first folder is shown

**Comment by hakandundar34coding** [comment]
Merging file list in both folders may fix the problem. Currently it tries to use one folder. If there is no such a folder it uses the other. The new version uses multprocessing and it gives error because 3 cores (for 4 core devixes) are used and there is one process. There may be errors for the processes on the other cores and these errors are not printed because of multiprocessing.

**Comment by hakandundar34coding** [comment]
Are the both directories real paths?
```
/lib/systemd/system
/usr/lib/systemd/system
```
On my system the first one is a link to the second one. 
The second one was ot found on your system (https://github.com/hakandundar34coding/system-monitoring-center/issues/40#issuecomment-1078648032).

**Comment by hakandundar34coding** [comment]
I have updated the source code. Can you follow these steps?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Switch to Services tab and check the service list.
- Also check the terminal window to see if there are errors.

On my system `/lib/systemd/system` is a link to `/usr/lib/systemd/system`. The second one was not found on your system. It looks like both of them are real paths on your system (https://github.com/hakandundar34coding/system-monitoring-center/issues/40#issuecomment-1078648032).

What happens if there are some installation cases which cause:
service files with the same name in the both folders?

**Comment by theofficialgman** [comment]
yes both of them are real paths. like I said, /usr/lib/systemd/system was created by installing a rogue program on my system. it isn't normally found there. there was only one file in it.

I have fixed that program which means the changes here are not necessary but still may be nice for other users.


on this updated source code. I still get an error and nothing in the list:
```
Traceback (most recent call last):
  File "/tmp/system-monitoring-center-master/src/MainGUI.py", line 284, in on_main_gui_tab_radiobuttons_toggled
    self.main_gui_tab_switch_func()
  File "/tmp/system-monitoring-center-master/src/MainGUI.py", line 518, in main_gui_tab_switch_func
    Services.services_initial_func()
  File "/tmp/system-monitoring-center-master/src/Services.py", line 176, in services_initial_func
    services_loop_func()
  File "/tmp/system-monitoring-center-master/src/Services.py", line 440, in services_loop_func
    services_data_rows_row_length = len(services_data_rows[0])
IndexError: list index out of range
```

note that I have fixed my install before running this. so I only have a `/lib/systemd/system` and no `/usr/lib/systemd/system` folder currently. v1.23.0 works correctly with only one folder.

**Comment by hakandundar34coding** [comment]
The source code is updated again. But you do not have the folder. What is the name of the application? Does the installation require very much effort? I do not know if it work on x86_64 systems (on virtual machine).

**Comment by theofficialgman** [comment]
same issue. honestly I would just revert all changes as I have fixed the offending application upstream. 
the app was this:
https://github.com/lakinduakash/linux-wifi-hotspot

in its install script, it installs a .service file directly to /usr/lib/systemd, even though that folder previously did no exist on my system, it created it. https://github.com/lakinduakash/linux-wifi-hotspot/blob/177c36c9e09409c58b6019b6ea80fe9edb5eb879/src/scripts/Makefile#L20

**Comment by hakandundar34coding** [comment]
This bug is fixed and the source code is updated.
It is tested on an old distribution on virtual machine.
I copied the service file in `/usr/lib/systemd/system` without installation for testing it.

I will close this issue. It affects a very small number of systems (in some cases) and it was fixed by you.
