### ISSUE TITLE
AMD GPU usage changes very slowly and incorrectly

### ISSUE THREAD

**Issue by theofficialgman** [hakandundar34coding/system-monitoring-center#109]
it takes an infinite time for the gpu usage percentage in system monitoring center to raise or lower to the actual value on AMD gpus

I am applying a test load causing 100% usage `/sys/class/drm/card1/device/gpu_busy_percent` but system montioring center only SLOWLY increases the value from 0% to 100% and never reaches it

this has been broken for a long time but I haven't reported it. is your table storing the values ever actually cleared or does it even have a max size?

**Comment by theofficialgman** [comment]
@hakandundar34coding bisected the version which it broke. 1.18 and earlier versions worked good. 1.19 and later have this issue

**Comment by hakandundar34coding** [comment]
Can you find line 632 and write 5 instead of 4?
or
Can you test the latest source code?

`        if Config.current_main_tab != 0 or Config.performance_tab_current_sub_tab != 4:`

How the results are affected?

The tab index was not updated after adding the Summary tab. It was not running rest of the code.

**Comment by theofficialgman** [comment]
solved with that change. since you already committed it, I will close this
