### ISSUE TITLE
can you provide a Dark theme option in General Settings?

### ISSUE THREAD

**Issue by pakair** [hakandundar34coding/system-monitoring-center#113]

**Comment by hakandundar34coding** [comment]
This feature was added by a contributor but I removed it after some tests. Because it switches from white theme to dark theme after windows is shown and causes a small increase for start time of the application. This is a system monitor and should be opened very quickly. Start time of the application is longer if CPU is under 100% load. Also time difference due to the theme switching is bigger if CPU is under 100% load.

**Comment by pakair** [comment]
Thank you for the explanation, I appreciate it.
