### ISSUE TITLE
Improvements to Process Treeview

### ISSUE THREAD

**Issue by JonnyCodewalker** [hakandundar34coding/system-monitoring-center#114]
Currently the process treeview is severely limited in usabiliy due to three things:

1. Either everything is collapse or everything is shown, making navigation painful.
2. No easy way to differenciate between "Userapp" like Firefox/Steam etc and system components (mostly important for less technically inclined users).
3. Parents do not have aggregate usage of their children but only their own, meaning it is hard to see what is actually using resources.

As for possible solutions:

1. This is probably the most complicated, but it might be enough to have a setting where only the last "leaf" is collapsed. This would result in  firefox-bin being shown, but the webprocesses being collapsed by default. avahi-daemon would also only be sytemd->avadhi-deamon (collapsed with another ->avahi-deamon inside). 

2. Again not sure, especially since I assume this project would like to be desktop independent. But an easy solution might be to visually separate userprocesses from root/other users  processes similar to how taskmanager in Windows does it with Apps & background apps [Image](https://blogs.windows.com/uploads/sites/2/2013/06/Windows_2D00_8_2D00_Task_2D00_Manager_2D00_Default_2D00_View_5F00_07A96EB9.jpg)

3. This is in my opinion the biggest problem with Treeview at the moment. It is really hard to gauge what program is using the most resources and might misbehave since you'd have to manually add up the usage per subprocess (and subprocesses subprocesses etc).
Easy solution here would be to have another column that shows "total usage" or show totalusage (own usage) ala `44%(2%)`.

Possible bonus:
It would be nice if there could be a devices tab where you can see what devices are currently connected to the system and manage them, however I am not sure how feasable this is to implement.

Even with all this system-monitoring-center is still by far the best "taskmanager" that Linux has to offer, so :+1:

**Comment by hakandundar34coding** [comment]
Total CPU usage of a tree branch feature will not be added. Because this application is written in Python and it is slower on several cases when compared to some other languages like C++/Rust. Summing operation for all process branches would increase CPU usage on the Processes tab.

Applications can be separated from the other processes by checking if a process has a window. But this feature would not work on systems with Wayland windowing system.

Rows related to kernel and user processes may be listed in separate lists in one of the newer versions of the application.

You can show/hide processes from other users by using `Show processes of all users` option on the customizations menu of the Processes tab.

![smc_processes](https://user-images.githubusercontent.com/90193017/191989017-aa428d93-3927-424f-9d80-dfb3bc55a222.png)

You can expand/collapse all rows by using `Expand all/Collapse all` actions from the right click menu on the Processes tab. After that you can expand/collapse some branches by using triangles at the beginning of the rows.

I thought about Devices tab several months ago. But there may be a separate application for this. Therefore, System Monitoring Center can be less complex and a lightweight application.

**Comment by JonnyCodewalker** [comment]
> Total CPU usage of a tree branch feature will not be added. Because this application is written in Python and it is slower on several cases when compared to some other languages like C++/Rust. Summing operation for all process branches would increase CPU usage on the Processes tab.

Understandable, if the impact on performance would be to big it doesn't make sense. Not sure if the data handling could be ported to a Rust/C library and the UI continue to be in Python, but I assume that would complicate the distribution of the application.

> Applications can be separated from the other processes by checking if a process has a window. But this feature would not work on systems with Wayland windowing system.

I assume wayland prevents you from seeing active windows? Maybe a way of doing it would be to keep a list of "user" applications by scanning .desktop files as to wether they are terminal apps, but that would probably be a) a performance problem again and b) difficult to keep up to date when the user is installing/removing programs. So probably not feasable. 

> You can show/hide processes from other users by using Show processes of all users option on the customizations menu of the Processes tab.

I was aware of that, maybe I am misremembering but I thought the default is "show all processes" which might be overcomplicating it for non savy users. If I am not misremembering maybe just changing the default value could work.

> You can expand/collapse all rows by using Expand all/Collapse all actions from the right click menu on the Processes tab. After that you can expand/collapse some branches by using triangles at the beginning of the rows.

I think defaults matter, but I would understand if you were reluctant to add a semicollapsed state since that would probably complicate the codebase quite a bit.

> I thought about Devices tab several months ago. But there may be a separate application for this. Therefore, System Monitoring Center can be less complex and a lightweight application.

If it does I have not heard of it, but ultimately that is more of a designchoice than a "bugreport" anyway, so if you prefer to leave it out that makes sense aswell (after all even on Windows they are different applications)

Thanks for the detailed feedback, and glad to see that some of my ideas might have been useful to you :)

**Comment by hakandundar34coding** [comment]
> I assume wayland prevents you from seeing active windows? Maybe a way of doing it would be to keep a list of "user" applications by scanning .desktop files as to wether they are terminal apps, but that would probably be a) a performance problem again and b) difficult to keep up to date when the user is installing/removing programs. 

I thought about using .desktop files for this feature. But some system applications may have .desktop files.  There may be a confusion. Currently these files are used for getting process images for the Processes tab.

> I was aware of that, maybe I am misremembering but I thought the default is "show all processes" which might be overcomplicating it for non savy users. If I am not misremembering maybe just changing the default value could work.

Default selection may be changed in newer versions.

--------------------------------------------

Distribution of this application is not easy. For example, a flatpak package can not be used because Flatpak does not support accessing all processes. Some other Flatpak alternatives are not safe as Flatpak. Accessing processes is required for several features of the application. Also there are a lot of packaging types (.deb, .rpm, etc). Currently I prepare .deb packages for some application stores. Using PyPI for distribution requires less effort. But this requires installing the system-wide dependencies by the user (mostly on ArcLinux. Because many dependencies are already installed on several systems.). This application is also used on a lot of Raspberry Pi devices and this application should be very lightweight due to this reason. As far as I know, old versions of some distributions are used on RB-Pi devices and these versions do not have GTK4. Using GTK4 would increase the performance on some cases. Because GTK4 supports hardware acceleration for GUI. GTK4 is not distributed on a lot of distributions by default. In short, there are some limitations for newer versions of some of the libraries (GTK4 for wayland support and HW acceleration) and distribution of the application. Currently this application is not packaged for several distributions by package maintainers.

Currently, development speed is low for this application. But bugs are fixed faster.

I will close this issue but you can write comments or open a new issue.
