### ISSUE TITLE
[Feature Request]  Use of Colors in Process enumerator section

### ISSUE THREAD

**Issue by The-Real-Admin-Guy** [hakandundar34coding/system-monitoring-center#127]
Hi,

I'm really enjoying using System Monitoring Center and I spend a lot of time in the "Processes" section...

It is real useful and well done.  I only have a rather basic suggestion:

I would find it easier to read through during analytical runs, where a more extensive use of colourful icons and text colouring be implemented...

Finding things at a glance is a bit too monochromatic to make it easy to rapidly id abstractions in the process load...

Also the process Tree while really useful actually adds significantly to the monochromatic noise...

Also I'm rather grateful you update so regularly.  It's a really good tool, very useful...

**Comment by hakandundar34coding** [comment]
All process images will not be colored. There may be changes for supporting more processes for process images.
Also there may be some colors for CPU, memory usages of the processes for recognizing processes easily. For example; bolder color for higher CPU usage.
There may be different images for kernel threads and other processes.

Some of these features (especially colors for CPU, memory usages) may not be added because of high CPU usage.

**Comment by The-Real-Admin-Guy** [comment]
Hi,
Thank you for responding...

Is performance a real issue when someone is actually perusing processes looking for malware or some abstraction?

I mean since the performance impact would be limited to the visual event? or Am I misunderstanding the load status being live even when not invoked?

Another idea, I'm playing with is for the addition of a checksum scan comparative with Virus-total.   

This would prove immensely useful since most desktop users have no antivirus or any type of anti-malware in Linux.   This is also a free api call since your tool is open source and not monetized....

Have a look here:
https://support.virustotal.com/hc/en-us/articles/360006819798-API-Scripts-and-client-libraries

In windows there is a panoply of process managers that provide the added benefit of a checksum verification.  

Checksum verifications is a simple process to implement and it is at the heart of Virus-total's usefulness.  As the file only needs to be checksummed locally everything else is based on push witch does come with some overhead.  However is only required once per live process without a checksum.

 It is rapid and requires little overhead and offers multiple benefits, such as an easy way to either whitelist and black list a process.

I would add the option to selectively or even automatically push files without a previously known signature to virus-total.

This would allow your tool to be used as a security check nice and proper and I don't think it would be to difficult to add another column to the process and services list to simply denote the virus-total score for the particular file...

To be honest this is probably the most important missing feature of Linux tools.  The total lack of visibility as to the security or vulnerability index of specific live executables...

You can verify a specific executable vulnerability based on the product status here:
https://cve.mitre.org/
https://www.cvedetails.com/

Just a thought!

Cheers!

Guy

**Comment by hakandundar34coding** [comment]
Cell color feature for CPU, memory (RSS) and disk speed/data columns is added. This feature is available for v2.1.0. It may be added for v1.x.x. Which version of the application is installed on your system?

Here is an example screenshot.
![cell_colors_dark](https://user-images.githubusercontent.com/90193017/204446737-2659388e-aa30-4d1b-87ef-bd743db42570.png)

There may be changes for process images in newer versions.

Currently, there are no plans for adding a feature that requires internet connection or additional services such as Virus-total.

Note: Cell colors are not visible because of a GTK4 bug. But the application supports it. Tests were performed by using GTK3.

**Comment by The-Real-Admin-Guy** [comment]
My current install is v1.34.0 using Pip install
It seems that the flat-hub pack is the one you keep most updated?

**Comment by hakandundar34coding** [comment]
v2.x.x is developed by using GTK4 GUI toolkit.
v1.x.x is developed by using GTK3 GUI toolkit.

There may be 1-2 new versions for v1.x.x. After that, there will be bug fix versions only.

They are very similar. But number of differences may increase in newer versions.

Flatpak version starts slower and CPU usage is higher for this version. Because it runs in sandbox and running commands to get host OS information causes higher CPU usage.

There will be new comments if there are new changes for Processes tab (process images).

There will be a new version for v1.x.x and it ill include the new features for Processes tab.

**Comment by The-Real-Admin-Guy** [comment]
I removed the pip version and now play around with the Flatpack version...

It is a bit more work to run as I must invoke the app store to get it to run...
Performance wise it seems very similar to the previous version I tested.  The main difference for me is there is a few more features to display.  

Colour in process view still do not work.

**Comment by hakandundar34coding** [comment]
There is a GTK4 bug in v2.x.x (Flatpak). Cell colors are not visible.
This feature is not added to v1.x.x (PyPI). It will be installable in 2-3 days. You can use the cell colored version if you update it (v1.x.x).

**Comment by The-Real-Admin-Guy** [comment]
Alright, thanks!

Over all this is really good work, I hope you will keep developing it...

Cheers!

**Comment by hakandundar34coding** [comment]
Example screenshot for the Processes tab (not published):
![processes_tab](https://user-images.githubusercontent.com/90193017/204612851-effa6402-bd05-4bae-8a87-b0ea13201dab.png)

Kernel threads are not colored. Other processes are colored. Also process images will be shown if they have their image in system folders. This feature will be usable for v1 and v2.

**Comment by hakandundar34coding** [comment]
I will write a comment here after a new version is available. This package will include the latest features for Processes tab.

**Comment by hakandundar34coding** [comment]
System Monitoring Center v1.35.1 can be installed.
Changes for process images and cell colors for Processes tab are included in this version (available on PyPI).

These features are also included in v2.1.0 (available on Flathub). But GTK4 toolkit has abug and cell colors are not visible.

I will close this issue. But you can write comments. You can also open a new issue for a different bug/feature.
