### ISSUE TITLE
[Feature Request] tray icon and minimize to icon

### ISSUE THREAD

**Issue by zen2** [hakandundar34coding/system-monitoring-center#157]
I would like to be able to launch it from tray icon and to be able to minimise the application to tray icon.

I don't know it it's possible to have an icon that represent the % of cpu/ram by filling colours of the icon to mimic the Sum up screen like a miniature.

**Comment by dCo3lh0** [comment]
Yeah, i just found your program, its fantastic, but i miss just this feature as have been said above,

**Comment by hakandundar34coding** [comment]
This feature may be added after at least 6-8 months later. Because a relatively new GUI toolkit GTK4 is used for this application. Currently, this toolkit has some memory leak problems and other bugs. Minimizing the application to the system tray may cause it to be keep running very long times and this may crash the application because of memory leak problems, etc.

Addidionally, several bugs of the application will be fixed after this time. This may prevent several problems during very long run times.

I will close this issue. But you can write additional comments. You can also open new issues for new features or bug reports.
