### ISSUE TITLE
[Feature Request] -- Tooltip To Show Full Command Line

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#159]
I noticed when the "Command Line" is too long (e.g. it is a java line with many parameters) then there is no way to see the full path and arguments. One would have to open the column as large as possible just to get an idea of what it is.

Could you have it so the tooltip for Command Line is able to show the entire command line? Since the command line can be really large due to arguments i would imagine also having page breaks would be useful instead of a really, really long tooltip.

**Comment by hakandundar34coding** [comment]
The source code is updated. Process tooltips are get from command line instead of process name.

You may run the application from the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code by using terminal and test Processes tab/menus etc. to check if there is an error because of the changes.

**Comment by amiga-500** [comment]
Insane how fast you are with these updates 🤯 Just checked and the new tooltips feature works perfectly!  Exactly how i like it!  Amazing!
