### ISSUE TITLE
"Not So Necessary" Feature Requests.

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#160]
Your app is by far leagues better than other system monitoring apps.  It has now become an invaluable tool in my daily activities.

What follows aren't necessarily feature requests but more "_it would be nice if.._" things.  Meaning, if not added it wouldn't make any difference to how i do things now.  I just thought i would share.

- **Processes & Services tab:** Each time i visit one of these tabs it would be nice if the keyboard focus was already set in the search input box, so if i start typing right away upon visiting this tab, it begins filtering the process/services to what i want immediately.

- **Processes tab:** Currently, to "End Process" via shortcut one has to use  "CTRL+T".  Makes total sense.  However, it would be nice if, alongside CTRL+T as an option, one could alternatively press the Del key to do the same thing.  This way, if e.g. one is using the cursor keys to navigate the list one just has to hit the nearby del key with the same hand to bring up the "Do you want to end this process?" instead of CTRL+T.  I come from a Windows background so each time i try to end a process i instinctively hit the delete key.  I also find it faster to press even though i could just hover my other hand over CTRL+T at all times.

- **Minimize Task Tray**: This was already discussed: #157 but just a few additional things to add to that:
     1. Hide to the task tray with or without the CPU/RAM display. Meaning, one has the choice.  For me, I would not want that info showing (animating) most times, but i do like to have SMC in the tray at all times. 
     2. To restore SMC from the tray i would prefer just a single-click, not a double-click.  Maybe its standard in Linux for tray icons to be restored via single-click?  If so then i'm cool with that.  But, maybe a user option to decide if its single or double-click to restore might be the way.
     3. Assuming task tray is a feature, then have an option to set SMC's startup state e.g. Start Minimized to Task Tray.  This way people can add SMC as a startup application on each boot without the distraction of it popping up on the center of the screen each time.

**Comment by hakandundar34coding** [comment]
About `Minimize Task Tray` feature:
@amiga-500, @zen2, @dCo3lh0,
There was an another user that wrote an email about a similar feature. Four users wrote about this feature so far. But this feature may be added after some time later ([details](https://github.com/hakandundar34coding/system-monitoring-center/issues/157#issuecomment-1518977739)).

About `Processes & Services tabs search entry focus` feature:
This may be added in a newer version. As an alternative way, Ctrl+F shortcut may be added for search entry (box) focus.

About `End process shortcut` feature:
`Del` shortcut may be added if more than one shortcut can be defined.

**Comment by hakandundar34coding** [comment]
Searchentry focus feature is added. `Ctrl+F` buttons can be used for focus of searchentries on Sensors, Processes, Users and Services tabs.

The application may be updated from Flatpak after about 4 hours.

---------------------------------------

`Del` shortcut is not added. Because, more than one shortcut can be defined for an action but only the first one is shown in the right click menu. Ending a process by using a single keyboard button is dangerous in this case. `Del` shortcut and an alternative shortcut may be added with an option in one of the newer versions of the application. But this depends on the popularity/download activity of the application.

**Comment by amiga-500** [comment]
> Searchentry focus feature is added. `Ctrl+F` buttons can be used for focus of searchentries on Sensors, Processes, Users and Services tabs. The application may be updated from Flatpak after about 4 hours.

Fantastic.  I will give it a try.

 
> `Del` shortcut is not added. Because, more than one shortcut can be defined for an action but only the first one is shown in the right click menu. Ending a process by using a single keyboard button is dangerous in this case.

Yea i figured the same.  Not a problem!  Granted, like Ctrl+T, the Del key would have also brought up the "_Do you want to end this process?_" dialog box, which would have prevented accidental process deletions.  But nonethless, im very happy with your app.  It's very impressive!  

Regards!

**Comment by amiga-500** [comment]
> Searchentry focus feature is added. `Ctrl+F` buttons can be used for focus of searchentries on Sensors, Processes, Users and Services tabs.

If im not mistaken ur app used to have the focus already set in the search field each time i visited the Processes/Services/Users tab.  I could have sworn i confirmed this a while back.  It seems that feature is now gone.  But the Ctrl+F still works though.

Just thought id let you know.

Using the latest SMC2.14.0 from FlatPak.

**Comment by hakandundar34coding** [comment]
I did not add a feature for SearchEntry focus after tab switches. There may have been problems because of some reasons. Last selected GUI objects grab focus if mouse button is clicked on them. This is the default behavior of the GUI toolkit.

You can follow these steps for checking the GUI object that has focus:
- Close the application and reopen it
- Open Processes tab and press Tab button on the keyboard
- Users tab selection button will be highlighted. The previous one was Processes tab. You can use Shift+Tab keys for changing the focused object in the reverse direction.

**Comment by amiga-500** [comment]
thx for the clarification :)
