### ISSUE TITLE
Sorting of columns in the Processes section does not match the clicked column

### ISSUE THREAD

**Issue by lorenzo0932** [hakandundar34coding/system-monitoring-center#162]
In the performance section if I click on any column except the first one the processes will be sorted with respect to the column immediately to the left of the selected one, for example if I select the "User" column they will be sorted by PID or if I select the "Memory RSS" column they will be sorted by cpu usage etc...

I attach a video about the problem, unfortunately the cursor is not visible but I hope you understand the problem
[Video del 2023-05-03 11-15-15.webm](https://user-images.githubusercontent.com/60674575/235878475-2ec2d73a-b344-4c53-abf7-ce00950bb48b.webm)

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated. There may be an update from Flatpak after about 4 hours.
There may be a new version in the other repositories that contains SMC v2 in about 1-2 weeks.

If you do not want to wait, you can follow these steps:

- Download the [updated](https://github.com/hakandundar34coding/system-monitoring-center/archive/8e1392810bc4a54a09db848bb5ae7ee06d3458ff.zip) source code
- Extract it and open `src` folder
- Copy the `Processes.py` file into the `src` folder that is in the System Monitoring Center installation directory.

**Comment by lorenzo0932** [comment]
Thank you so much for your helpfulness! I will close the issue and wait for the release of the new updated version on Flathub.

**Comment by hakandundar34coding** [comment]
The application was updated in Flathub yesterday. The version number did not change. The latest changes are added.
