### ISSUE TITLE
Add ability to select multiple processers [Feature Request]

### ISSUE THREAD

**Issue by coreybruce** [hakandundar34coding/system-monitoring-center#172]
Hey again, this has been one thing that has bothered me for a while that you can't do compared to Gnome System monitor, please add the ability to select more than one process so you can pause, change priority, kill etc multiple processes at once.

E.g
![Screenshot from 2023-05-20 21-45-27](https://github.com/hakandundar34coding/system-monitoring-center/assets/8393780/2ccaef44-eeda-486f-ad3d-9bd2f658ed80)

**Comment by hakandundar34coding** [comment]
This feature may be added in one of the new versions.

**Comment by hakandundar34coding** [comment]
Multiple process selection feature is added and the source code is updated.

Details:
Multiple processes can be selected, stopped, continued, ended, priorities can be changed, details windows can be opened.
Currently, max. number of details windows is 8 (3 for Flatpak environment) for preventing GUI responsiveness problems because of high CPU usage.

The application may be updated by using:

- Flatpak in about 4 hours
- Other repositories in about 1-2 weeks.

I will close this issue. But you can write comments if there are problems about this feature.
