### ISSUE TITLE
Transparency mode for games [Feature request]

### ISSUE THREAD

**Issue by vladimirfiffie** [hakandundar34coding/system-monitoring-center#176]
I would like to know if it is possible to do a transparency mode where you see the graph like in Xbox game bar. It would be helpful for seeing GPU usage for my case. I currently have the window on top so I can see the GPU usage but it obstructs my view in the game since it is the whole window, but minimized.

**Comment by amiga-500** [comment]
if im not mistaken this app uses the pyGTK toolkit for its gui. So it would be fairly trivial to allow transparency mode to be enabled via: `Gtk.Window.set_opacity()` ... i assume this app already has a "stay on top" feature (so the app never leaves the screen as u play games).

The author is very active so there is a good chance he will comment soon.  

if you're itching to have the feature now, the author's coding skills in the app is pretty clean, so you could add the feature yourself very quickly on your pc (its just raw python scripts).  Granted you do need to know some coding but even for me who doesnt know python i have been able to tweak the code easily since its fairly intuitive.

**Comment by hakandundar34coding** [comment]
What do you want?

- Option for changing only transparency of the main window.

or

- A semi-transparent simplified window.

The first one may be added in about 1-2 weeks.
The second one may be added after some months. Because there will be some other new features and changes before this feature.

**Comment by hakandundar34coding** [comment]
An option for window opacity is added.
This option affects only main window of the application. Child windows, dialogs, tooltips, etc. are not affected. Otherwise, several controls may be harder.

v2.17.0 can be installable in about:
- 4 hours from Flatpak
- A few days to a few weeks from other repositories

I will close this issue. But you can write additional comments or open a new issue for bugs, etc.
