### ISSUE TITLE
some opensuse distro based compatibility

### ISSUE THREAD

**Issue by Ygarr** [hakandundar34coding/system-monitoring-center#18]
1. While install requires glx-util, but Mesa-demo-x presents instead
2. Missed "_ O X" window buttons
3. "System tab is empty"
![Screenshot_20220114_084233](https://user-images.githubusercontent.com/14309871/149470007-066bfd54-0ef0-44e9-b0be-1e4aaf4a3298.png)

lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20220111
Codename:       n/a

**Comment by hakandundar34coding** [comment]
1. How did you install the application?
2a. What is the current desktop environment and window manager on your PC?
2b. Are window buttons shown on other application windows?
3. Can you run System Monitoring Center from terminal, switch to System tab and write errors?

**Comment by hakandundar34coding** [comment]
About 21 days have been passed since last comment but you did not write any information about the questions.

1. I do not know the packaging system on your PC. You can change the dependeny and you can prepare a package by using one of the scripts in the ```packaging_scripts``` folder.
You can change dependencies from:
```control``` file in the debian folder    (on debian-like systems)
```system-monitoring-center.spec``` file    (on RPM-based systems)
```PKGBUILD```    (on archlinux-based systems)

2. I have tested the application on several systems with GNOME, XFCE, KDE Plasma and Cinnamon desktop environments on virtual machines. There was no problem with the window control buttons.
Some applications with GTK GUI may have problems on different distributions but I did not learned something about desktop environment and window manager of your system.

3. I have added an error handling for a depencency which may not be installed on some systems. This may fix the problem on the ```System``` tab.

I will close this issue but you can write comments or you can open a new issue if there are another problems.

**Comment by Ygarr** [comment]
1. I`ve installed with rpm as usual opensuse package on usb flash
    -DE is PLASMA on Geckolinux
    -Yes the they were present 
2. Yeah, I will re-test the tool a bit later

**Comment by hakandundar34coding** [comment]
I have tried to test the application on GeckoLinux (with KDE Plasma DE) on virtual machine (without installing on virtual machine).
GeckoLinux details: GeckoLinux_ROLLING_Plasma.x86_64-999.220115.0

There was a dependency problem. I do not know details of this distribution and I ran the appliation from the code without installing it.

There was no visual problem with window control buttons (minimize, maximize, etc.).
System tab worked.
Here is a screenshot but icons are not displayed because the application is run from the code without installation.

![os_smc_test](https://user-images.githubusercontent.com/90193017/152813697-a44a35ce-7285-4fa4-be95-004e5ca861cb.png)



You can generate a package by using one of the packaging scripts if it works without problems on GeckoLinux. But dependencies may be renamed because some dependency names are different on different distributions.

For example:
glx-utils (on Debian based distributions)
mesa-utils (on some RPM based distributions)

I have tested the script on some RPM based distributions and it worked. It uses ```system-monitoring-center.spec``` file for getting required dependencies.
