### ISSUE TITLE
Showing multiple graphs at the same time

### ISSUE THREAD

**Issue by johnyboro** [hakandundar34coding/system-monitoring-center#182]
Love the app, I run it on my pc case display

The problem is i like the colorful graphs so much that i would like to have multiple of them, for example 4: gpu, cpu, ram, disk, all at once. Maybe some click mechanic so ctrl+ click would open multiple.
No idea how hard this is to add, I'm no developer yet.

Keep up the great job <3

**Comment by hakandundar34coding** [comment]
Currently, CPU, RAM, Disk and Network information are shown at the same time on Summary tab.
GPU usage is not shown at the same time. Because getting GPU information increases CPU usage very much when compared to other information. There may be an option for showing GPU usage on the Summary tab in one of the newer version. But this requires some detailed changes.

Additionally, there are no plans for adding a new tab for showing more graphics.

Can you give more details if you want a different feature about graphics?

----------------------------------------

I will close this issue. But you can write additional comments.
