### ISSUE TITLE
No Disk displayed or usage shown for USB system disk ver 2.17.0

### ISSUE THREAD

**Issue by spsf64** [hakandundar34coding/system-monitoring-center#186]
Hi, thanks for this great program!
I usually install linux to external flash drives and noticed the read/write disk is not shown in the summary tab. 
I also checked disk tab and selected SDA (which is my external USB drive), and it does not recognize it. The only displayed disk is my internal nvme that is not even mounted
I think you can see all data in the attached image.
This is endeavouros / archlinux spin
Let me know if you need any extra information...
Thank you

![img2](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/1508a364-9ed6-497f-b03d-dfeea30f0a0e)

**Comment by hakandundar34coding** [comment]
Can you test it by using v2.17.1?

**Comment by spsf64** [comment]
> Can you test it by using v2.17.1?

Sorry for this late reply, just tested 2.17.2, now if I manually select the disk (from disk tab) is shows in the summary tab.
The problem seems to be the program does not detect the usb drive as a "system disk", see images...
Also a suggestion; in the summary tab, is it possible to show which disk is being monitored? Like: sda or nvme1, etc...



![Screenshot_2023-07-06_10-48-48](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/0a42cec2-a54c-4cb5-8dc9-5f79af939b6c)

![Screenshot_2023-07-06_10-49-13](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/8ab609be-ada7-491c-9014-e04aad4ce0d6)

![Screenshot_2023-07-06_10-50-53](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/242fce8b-2799-4bd7-9e86-0484884169c3)

**Comment by hakandundar34coding** [comment]
Selected disk and network card names will be added to Summary tab.

----------------------------------

About system disk detection:
Can you share output of these commands?
```
cat /proc/mounts
cat /proc/cmdline
```

**Comment by spsf64** [comment]
> Selected disk and network card names will be added to Summary tab.
> About system disk detection: Can you share output of these commands?


Thanks! Here you go:

------------------------------------
_Removed some system information._

**Comment by hakandundar34coding** [comment]
I get the required information. Your system information is removed from your comment. Some information may be sensitive.

**Comment by hakandundar34coding** [comment]
I got the required information. Your system information is removed from your comment. Some information may be sensitive.

**Comment by spsf64** [comment]
> I got the required information. Your system information is removed from your comment. Some information may be sensitive.

Thanks a lot! Hope it helps to solve the problem...
Have a nice day

**Comment by hakandundar34coding** [comment]
I do not know if it was a security problem.

------------------------------------

Does the application show any disk as system disk?

I will fix this problem tomorrow.

**Comment by spsf64** [comment]
> Does the application show any disk as system disk?

No, lol!! Just checked booting from internal ssd with similar layout, none of the partiions is displayed as "system disk"


linux@archlinux ~ > lsblk -f
NAME        FSTYPE      FSVER LABEL     UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sr0                                                                                         
nvme0n1                                                                                     
├─nvme0n1p1 vfat        FAT32           3EF9-XXXX                             419.4M    18% /boot
├─nvme0n1p2 ntfs              Win11     5634FD0534XXXXXX                                    
├─nvme0n1p3                                                                                 
└─nvme0n1p4 crypto_LUKS 2               569bb707-c2a4-45ff-8ff8-d3c802XXXXXX                
  └─luksdev ext4        1.0   ArchNvme4 4b008b54-d345-4bc1-acb4-e15f4bXXXXXX  149.2G    34% /
linux@archlinux ~> 


linux@archlinux ~> lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sr0          11:0    1  1024M  0 rom   
nvme0n1     259:0    0 953.9G  0 disk  
├─nvme0n1p1 259:1    0   512M  0 part  /boot
├─nvme0n1p2 259:2    0   100G  0 part  
├─nvme0n1p3 259:3    0    16M  0 part  
└─nvme0n1p4 259:4    0   250G  0 part  
  └─luksdev 254:0    0   250G  0 crypt /

**Comment by hakandundar34coding** [comment]
Probably, it is because of the encrypted disk.

Can you follow these steps?
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal in `src` folder
- Run the following command: `python3 ./run_from_source.py`
- Open Disk tab and check system disk information
- Also share the errors in the terminal output

-----------------------------------

Additionally which disks are system disks for your two OSes? `sda1` and `nvme0n1p4`?
`sda` and `nvme0n1` are parent disks. One of children of these disks are system disks.

**Comment by hakandundar34coding** [comment]
Probably, it is because of the encrypted disk.

Can you follow these steps?
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal in `src` folder
- Run the following command: `python3 ./run_from_source.py`
- Open Disk tab and check system disk information (sda1, sda2 or dm-0?)
- Also share the errors in the terminal output

-----------------------------------

Additionally which disks are system disks for your two OSes? `sda1` and `nvme0n1p4`?
`sda` and `nvme0n1` are parent disks. One of children of these disks are system disks.

Can you share output of this command?
`ls -l /dev/disk/by-partuuid`

**Comment by spsf64** [comment]
Ok, now I have plenty of screenshots, I think I wiil post on pastebin...
I run from source and the dm0 (which is a partition) shows as system disk: yes, but sda (which is the actual disk) does not... 
I am no expert in hardware, but I think the real disk is sda, isn't it?
Also, there are no errors in terminal

Just to make it clear, I have 1 computer with 1 nvme internal.
I have some usb3.0 sticks with archlinux and other variants installed, I do this instead of virtualbox. 
On all of them I always do uefi/gpt, luks and 2 partitions; 1 for efi (mounted on /boot) and 1 for / luks (root, home and everything else)
Normally when booted from usb, they identify (lol!) as /dev/sda (sda1, sda2 and luksdev). See attached image.

I will post the screenshots later, let me know if you need some more info....
.
.
.
.
Booted from USB and internal nvme0n1 mounted:

![boot from usb](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/646be301-a4a5-4c90-b78e-d29cf4447acc)

.
.
.
.

Booted from USB and internal nvme0n1 NOT mounted:

![nvme not mounted](https://github.com/hakandundar34coding/system-monitoring-center/assets/1877391/e938a1d0-70ae-4cae-9c32-7d4cfc02c05c)

**Comment by hakandundar34coding** [comment]
I have used encrypted disk for adding support for these disks. I do not have much experience with using them.

I think OS is installed on sda2 which is a partition (child disk) of sda.
But system disk and disk that has filesystem is dm-0.
dm-0 disk is generated because of disk encryption.
Probably, luksdev name is set by OS during disk encryption setup. There is an example in this [comment](https://github.com/hakandundar34coding/system-monitoring-center/issues/153#issuecomment-1523574060).

You can select dm-0, if you want to see used, free space information for system disk. There is such a difference because sda2 does not have a filesystem.
About disk read/write speeds:
Probably, sda2 and dm-0 have similar disk speeds.

**Comment by spsf64** [comment]
Thanks for installing and trying to fix this!
I agree with you about the system disk, anyway, the summary tab showed the read/writes for the correct disk by default when started, which is good!
Yes, sda2 and dm-0 showed similar speeds!

**Comment by hakandundar34coding** [comment]
Selected disk and network card names are added to Summary tab graphics.

This feature will be used in SMC v2.17.3 in about a few days.

Screenshot of the Summary tab after the changes (see sda2 and wlp3s0 device names):
![smc_device_name](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/3fb52264-171e-4b18-9d6a-b5fdc5daad47)

**Comment by hakandundar34coding** [comment]
Are there bugs that are not fixed?

**Comment by hakandundar34coding** [comment]
I will close this issue. But you can write comments if there are bugs that are not fixed.

You can also open a new issue for new bugs, new features, etc.
