### ISSUE TITLE
.deb package for SMC v2

### ISSUE THREAD

**Issue by sbstn87** [hakandundar34coding/system-monitoring-center#209]
Hi,

since the v1 version does not receive any feature updates, could you perhaps provide a .deb package for the SMC v2?

You write that non-Flatpak versions of the application has higher performance (start speed, CPU, RAM usage) and for a system monitoring app this is an important point.

**Comment by hakandundar34coding** [comment]
@theofficialgman,

Does uploading .deb packages of SMC v2 cause problems on systems using Pi-Apps?

What can be done for preventing these problems?

- Adding also SMC v2 with `2` in its name?

- Checking for main version number and allowing intallation of SMC v1 only?

SMC v2 uses GTK4. It is a hardware accelerated GUI and consumes about 2x RAM when compared to SMC v1. Probably, many of R-Pi devices does not have 8 GiB RAM.

**Comment by theofficialgman** [comment]
> Does uploading .deb packages of SMC v2 cause problems on systems using Pi-Apps?
>
> What can be done for preventing these problems?
> 
> * Adding also SMC v2 with `2` in its name?
> * Checking for main version number and allowing intallation of SMC v1 only?
> 
> SMC v2 uses GTK4. It is a hardware accelerated GUI and consumes about 2x RAM when compared to SMC v1. Probably, many of R-Pi devices does not have 8 GiB RAM.

@sbstn87 
GTK4 isn't available in debian bullseye (11) or buster (10). piOS does not have a release on bookworm (12) yet which is the first debian version to have GTK4 support. So the simple answer is even if you have SMCv2 available as a deb we can't use it on piOS

You are welcome to post additional github releases under a `v2.XXX.XXX` tag. Pi-Apps has a very configurable github actions based updater and we can parse all github releases for the highest `v1` tag.

**Comment by sbstn87** [comment]
What I had in mind is having SMCv2 packaged as a .deb file to install it natively on Debian 12 and its derivatives.

**Comment by hakandundar34coding** [comment]
There will be a .deb package for the next version of SMC v2 in about 1 week.

I asked some questions about package of SMC v2. Because .deb packages are also used by an application store (Pi-Apps).

@theofficialgman wrote answer by adding tag of your account (it may be written accidentally). Do you have questions?

**Comment by theofficialgman** [comment]
> @theofficialgman wrote answer by adding tag of your account (it may be accidentally). Do you have questions?

yeah sorry my bad, that tag was accidental

**Comment by sbstn87** [comment]
> There will be a .deb package for the next version of SMC v2 in about 1 week.

That's great, thank you.

**Comment by hakandundar34coding** [comment]
A .deb package of SMC v2.21.0 is shared.
But there may not be .deb packages for all new SMC v2 versions. Generating package for SMC v1, v2, Flatpak, etc. and testing them requires additional time.

I will close this issue. But you can write additional comments or open new issues for bugs, new features, etc.

---------------------------

@theofficialgman,

Does calling you from comments by adding tag bother you? Do not hesitate to write here if it bothers you.

**Comment by theofficialgman** [comment]
@hakandundar34coding I'm not bothered at all. Feel free to tag me anytime you think a change you plan on making might be relavent to packaging. I actually like having a heads up like this.

**Comment by theofficialgman** [comment]
@hakandundar34coding just wanted to let you know. At pi-apps we have now (for a few weeks) implemented detection of `gir1.2-gtk-4.0` and if present install v2 instead of v1 (so effectively jammy/bookworm and newer distros with use v2).

I mentioned before that the use of `v1` vs `v2` tags on the releases is used to detect and update each version accordingly but never showed you how we do that. Incase you are curious this is how we obtain that info from the github api and parse it with `jq`
https://github.com/Botspot/pi-apps/blob/master/.github/workflows/updates/System%20Monitoring%20Center.sh

No changes are necessary at this time. I just wanted to update you on what we are using.

**Comment by hakandundar34coding** [comment]
@theofficialgman

There are no plans for changing version names (starting with v1/v2). But this is a less fragile solution in the side of SMC repository. Additionally, in both cases, you know if there are problems about updates. There are details about results of updates in automatic pull request comments.
