### ISSUE TITLE
F5 key shortcut for refreshing tabs without waiting update interval of the application

### ISSUE THREAD

**Issue by badcast** [hakandundar34coding/system-monitoring-center#224]
It would be nice to focus on automatic data updates, but if you continue to receive more private updates, it will increase the collection of information about the system with high accuracy. This, for example, was supported in the "Task Manager". Anytime, anywhere, without going to Setup.

![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/d692647a-6060-4b7b-be2d-3cda5fa74745)

**Comment by hakandundar34coding** [comment]
The feature is added. You can test it by using the latest source code. It works on every tab.

**Comment by badcast** [comment]
It works, but with a long hold, the program completely stops its work and does not respond to my other actions. After releasing, the program resumes with a delay.

**Comment by hakandundar34coding** [comment]
Can you write name of the tab that this behavior is observed?

How do you use this feature? Pressing F5 key one time or long time?

A delay will be added for preventing refreshing tabs very frequently if F5 key is pressed very long. 0.25 seconds may be used for many tabs.

**Comment by badcast** [comment]
This problem exists on any tabs.
when pressing the F5 key once, there is no delay.
when holding down the F5 key, there is a time delay.

**Comment by hakandundar34coding** [comment]
Can you test it again by using the latest source code?

**Comment by badcast** [comment]
Hi! I've just launched a fresh one.
Is it possible to reduce the interval to 0.1 ?

**Comment by hakandundar34coding** [comment]
It may block the GUI on systems with low performance. You can edit config file manually for testing. After testing, you can restore the previous value. You can find this file in `/home/[USERNAME]/.config/system-monitoring-center/` directory.

**Comment by badcast** [comment]
Thank you. I have no questions about this "Issue"

**Comment by hakandundar34coding** [comment]
Is the blocked GUI problem fixed after the latest code changes?
Is time delay value for preventing GUI freeze is very large? It is 0.25 seconds for Summary, CPU, Memory, Disk, and Network tabs.

**Comment by badcast** [comment]
I checked the latest code, it works without delay.
0.25 is probably acceptable if not all processors have stability.

However, I didn't know about
$HOME/.confg/system-monitoring-center/config.txt
[General - General]
update_interval = 0.1
thereby suppressing their desires settings.

**Comment by hakandundar34coding** [comment]
Settings are saved into this file. There is no check for these settings before using them. For example, minimum update interval is 0.5 seconds on the General Settings window. But you can set is as 0.07 or 24.6 seconds. GUI responsiveness depends on performance and load of your system. CPU tab may be responsive but Processes tab may not be responsive if update interval is set as a very small value.

**Note:** Update interval and time delay values are different. Time delay value for preventing GUI freeze is not changed by user and it is not saved into setting file.

Additionally, the application may crash if some values are changed manually. For example, if `show_cpu_cache_type` value is set as `abcd` or `Socket`, it craches when CPU tab is opened. Currently, 2 values are supported for this setting: `socket` and `core`. `Socket` can not be used instead of `socket`.

**Comment by badcast** [comment]
Thanks for the details. I will stick to the boundaries.
