### ISSUE TITLE
Is it possible to support new VIEWS in the summary window?

### ISSUE THREAD

**Issue by badcast** [hakandundar34coding/system-monitoring-center#225]
Is there an opportunity to supplement (1)
this window, for example, to make a new graphic.
If possible, I would support the design and look (2).

![image(1) and (2)](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/e749a93c-b972-4a47-ad15-b1a1de579aee)

If possible, you can provide documentation or a link for me to start doing this to supplement the list ( 1 )

IF PLANNED

**Comment by hakandundar34coding** [comment]
There was an issue about summary graphics. I wrote a [comment](https://github.com/hakandundar34coding/system-monitoring-center/issues/193#issuecomment-1640209518) about new summary graphics.

An option may be added to summary tab customization menu for selecting different summary graphics (current one and new one) if new graphics are added.

You can share it or send a pull request if you have design ideas for summary new graphics. It may take a long time to prepare new graphics if you do not know cairo graphics. You can review Summary.py file for details about the graphics. You can do a web search for Python-cairo drawing. There are simple examples. You can use this [link](https://lazka.github.io/pgi-docs/#Gtk-4.0/classes.html) for learning usage of GTK4. Simple GTK examples can be found by doing a web search.

You can draw it by using a drawing tool and share it before coding it and sending a pull request for it. It may not be merged because of some reasons (design, performance, etc.).

You can download the source code, clear the code under current summary graphics function and study under this drawing function.

The list is used for preventing movements of other tab title buttons during tab selection. You can open Sensors and GPU tabs repeatedly. Sensors tab button is moved. It is a single button. But a lot of buttons are moved if Summary tab and another tab is selected if a list is not used. This list is not added for graphic selection.

**Comment by hakandundar34coding** [comment]
Answers are written in the previous comment. I will close this issue. But you can ask more questions and write additinal comments.

**Comment by badcast** [comment]
Thanks for the help

**Comment by hakandundar34coding** [comment]
More details can be written if you ask. :) There was limited information in the answer (a few details about the graphics).

**Comment by badcast** [comment]
I will be very strict with questions, can you handle it? : )

**Comment by hakandundar34coding** [comment]
Did you mean asking too many questions?
I can answer some of them. You can also ask your questions by using e-mail. Additionally, you can review examples on the web. You can review code of SMC. But some improvements are required for code of graphics of the application.
