### ISSUE TITLE
Request - System tab suggestions

### ISSUE THREAD

**Issue by linuxlite** [hakandundar34coding/system-monitoring-center#25]
Please consider the following. Takes into consideration all distros, including custom named ones.
Please also consider reducing the Kernel Version in System tab, have to stretch window out to massive size to read it all.
Because each PC is unique, remember window size would be a great solution also.

In System.py

replace:

```
    for line in os_release_output_lines:
        if line.startswith("ID="):
            os_name = line.split("ID=")[1].strip().title()
            continue
```

with:

```
    for line in os_release_output_lines:
        if line.startswith("PRETTY_NAME="):
            os_name = line.split("PRETTY_NAME=")[1].strip(' "')
            continue
```

and....

`    label8101.set_text(f'{os_name} - {os_version}')
`

with:

`    label8101.set_text(os_name)`

The latter looks a lot tidier, and the former helps identify custom or modified distros. like ours.

Screenshot before and after:

![before](https://user-images.githubusercontent.com/5382578/152641930-749b7fbd-6744-427c-a8b4-89e3976ecc54.png)

![Screenshot_2022-02-06_01-15-15](https://user-images.githubusercontent.com/5382578/152641913-d6436b0c-021b-4ca6-b171-8b936d72c88d.png)

Notice in the screenshots, there is extra background image instead of just the window itself.
I REALLY like this application, it has tremendous potential :)

**Comment by hakandundar34coding** [comment]
Are there any ways to determine if this is a custom/modified distribution?

Both of the OSes show ```Debian``` as ```Based On``` information.

Can you write here all of the information in the ```/etc/os-release``` file?

**Comment by linuxlite** [comment]
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Linux Lite 5.8"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by hakandundar34coding** [comment]
There are different Ubuntu based distributions. For example Linux Mint. OS and version information shows information of Linux Mint instead of Ubuntu and ```Ubuntu``` is shown as ```Based On``` information. Screenshot of the System tab:

![system_monitoring_center_on_linux_mint](https://user-images.githubusercontent.com/90193017/152691620-bcc7ddd4-fa40-4fe7-86a4-551889d72771.png)

A change about OS name and version information on System tab is not required. I do not know if this is applicable to Linux Lite.

An option for remembering window size can be added.

**Comment by linuxlite** [comment]
Have you looked at "PRETTY_NAME" across a variety of distribution types? eg. Fedora, Gentoo, Slackware, Debian, Arch ?

**Comment by hakandundar34coding** [comment]
I have read the documentation from this link:
https://www.freedesktop.org/software/systemd/man/os-release.html

The application will get OS name and version information by reading ```NAME=``` and ```VERSION=``` lines instead of ```ID=``` and ```VERSION_ID=```.

In general, ```PRETTY_NAME=``` line contains ```NAME=``` and ```VERSION=``` information together. But there are ```Name:``` and ```Release:``` information areas on System Monitoring Center GUI. ```NAME=``` and ```VERSION=``` lines from the file are required.

Also these information will be shown as ```NAME= - VERSION=``` on top top the ```System``` tab as ```Operating System Name and Version``` information. For example: ```Pardus GNU/Linux - 21.1 (yirmibir)```. This line will be consistent with the next line (```Computer Name And Model``` information). These two lines are in the same line with the Reload button.

You can try the latest code (you can replace only System.py file):
https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip

You can share here if you have additional examples.

Here are some ```/etc/os-release``` file examples of different distributions which are run on virtual machines:

![al_os_release](https://user-images.githubusercontent.com/90193017/152769441-4b51dc16-b270-4e20-a9c6-51d86922939d.png)

![fd_os_release](https://user-images.githubusercontent.com/90193017/152769444-8930be38-79fe-4ad7-a84f-d87db850f0d9.png)

![lm_so_release](https://user-images.githubusercontent.com/90193017/152769448-2a5c7c3c-c8e2-456d-96ad-0cffa02ab1cb.png)

![mj_os_release](https://user-images.githubusercontent.com/90193017/152769451-523ae7db-b8dd-4243-857d-7b37edeeeed0.png)

![zo_os_release](https://user-images.githubusercontent.com/90193017/152769453-f58d8712-6cb0-4a26-89ca-c088a76011ed.png)

**Comment by linuxlite** [comment]
PRETTY_NAME is much better to use. It solves both issues in one hit.

**Comment by hakandundar34coding** [comment]
**About OS name:**
But there may be a lot of space characters in ```PRETTY_NAME``` and in version part of this information. Name-only and version-only information may not be get exactly.

Are there any problems with changing the information in ```/etc/os-release``` file in Linux Lite?

**About Kernel Version:**
This information is shorter on some systems. Length of this information is different on different distributions. Format of this information also different on some OSes.
There are longer information areas on System Monitoring Center. For example, network card vendor-model, GPU vendor-model, etc.
This information can be selected by right clicking and selecting ```Select All``` and it can be copied. Or it can be selected by triple clicking.
Currently I have no plans for changing this information.

**About remembering the window size:**
I have plans for this feature. But before that I will change Config.py module because every new setting requires resetting all settings of System Monitoring Center.

I will close this issue. You can open a new issue if there are another bugs/problems in the code.

**Comment by linuxlite** [comment]
Spaces in names is not an issue, that's easily taken care of in Python.
The same goes for other fields including Kernel version, so easy to character limit per field.
Without these sensible changes, we may have to fork it and implement ourselves, no problem.

**Comment by hakandundar34coding** [comment]
An option for remembering window size is added.
It can be tested by downloading the latest source code. The latest source code will be included in a package in a few days.
