### ISSUE TITLE
[Feature Request] All in single time varying plot

### ISSUE THREAD

**Issue by hsbasu** [hakandundar34coding/system-monitoring-center#28]
Currently CPU Performance, RAM & Swap, Network shows plots with single color. It would be much more user-friendly and attractive if the following can be implemented:
1. [x] In CPU Performance, show Per thread performance in a single time varying plot with different colours for each thread.
2. [x] In RAM and Swap, Show both of them in a single time varying plot with different colours for each of them.
3. [ ] Same goes For Download and Upload in Network
4. [ ] All GPUs in a single time varying plot with different colours for each of them.

For these suggestions, Gnome System Monitor can be used as reference.

PS: I really love this application as it truly satisfies the name of a system monitor. I would hope all the Linux distro use it as their default system monitor.

**Comment by hakandundar34coding** [comment]
CPU usage line plots per-core feature may be added in the newer versions. But these plots may be in separate graphs in the same tab instead of a single graph with multiple lines. Because it would be hard to understand the graph if there are more than 3-4 logical cores. Especially on systems with low resolution screens, there may not be enough space to enlarge the application window to make graph larger.

Also other data such as disk read/write speed and network download/upload speed plots may be redesigned for showing multiple device data at the same time.

But selecting a different GPU has no effect on FPS measurement. It is reset only. Measurement is made for the GPU which runs the application. An explanation may be added for this situation (under the GPU selection combobox on the GPU tab customization menu).

Currently, addition of the graph redesign changes depends how widely the application is used.

I will close the issue but you can write additional comments.

**Comment by hakandundar34coding** [comment]
It has been a long time since the last comment but there are some updates about this issue.
This is feature is added in v1.8.0 and it is downloadable:

- Feature for plotting CPU usage history for all cores as line chart.

Similar feature for disk and network cards may be added in newer versions.

**Comment by hsbasu** [comment]
> It has been a long time since the last comment but there are some updates about this issue. This is feature is added in v1.8.0 and it is downloadable:
> 
>     * Feature for plotting CPU usage history for all cores as line chart.
> 
> 
> Similar feature for disk and network cards may be added in newer versions.

I just checked. It looks awesome. Is it possible to add another feature: different random colors for different cores?

**Comment by hakandundar34coding** [comment]
CPU usage of each core is shown as separate line charts and core numbers are shown on top-left corner of each chart. Why do you want different colors? It would be distracting. Also cores would not be distinguishable if there are a lot of cores (16, 32, ...). Because colors will be close to each other.

But other features may be added in newer versions (https://github.com/hakandundar34coding/system-monitoring-center/issues/28#issuecomment-1081657127).

![smc_per_core](https://user-images.githubusercontent.com/90193017/161262771-8b9dc660-d481-4678-8c07-552e8500c9f1.png)

**Comment by hakandundar34coding** [comment]
The latest version (v1.13.0) supports plotting

- RAM and swap memory
- Disk read/write speeds of all disks
- Network download/upload speeds all network cards

at the same time.
Currently there is no plan for plotting GPU usage data of all GPUs at the same time. Because CPU usage will be very high for this feature.

Here are a few screenshots:
![smc_memory_plot](https://user-images.githubusercontent.com/90193017/166094815-aafbf940-83d2-4f7f-bd97-5bc58f926d7c.png)
![smc_disk_multiple_plot](https://user-images.githubusercontent.com/90193017/166094822-dfd4715d-f79c-4380-8062-c4d1070a01a9.png)
