### ISSUE TITLE
Select foreground color does not close

### ISSUE THREAD

**Issue by anselal** [hakandundar34coding/system-monitoring-center#32]
Version: system-monitoring-center_1.5.0_all.deb
OS: Ubuntu 20.04.4

Fresh install of the app, CPU tab => cog => select CPU Usage (Per Core) => Foreground

then the pop does not close neither with Cancel nor with Select

**Comment by anselal** [comment]
PS: Happened only once. After I closed and re-opened it seems to work

**Comment by hakandundar34coding** [comment]
I have tested it now. There was no bug after trying a few times.

I will close this issue. But you can write comment if the color chooser dialog does not work. I will reopen the issue and fix the problem.

**Comment by hakandundar34coding** [comment]
I have found the problem.

Window close button (X) is shown on some desktop environments and clicking on it causes the problem.
But this button is not shown on several dekstop environments and ```Cancel``` button is shown.
It works without errors if ```Cancel``` button is used instead of (X).

I have fixed the problem. The lastest source code contains the updated code. You can download the latest [code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) and generate a package by using the script in the ```packaging_scripts``` folder.

A package (v1.7.0) with the latest code will be available in a week.

**Comment by anselal** [comment]
thnx for fixing the issue. Glad I could contribute.
Will wait for the new release !!!
