### ISSUE TITLE
Feature request: add File system view (like Gnome system Monitor)

### ISSUE THREAD

**Issue by Trikenstein** [hakandundar34coding/system-monitoring-center#37]
Hi,

Discovered this wonderful tool thanks to the TechRepublic's article [How to install one of the best system monitors for the Linux desktop](https://www.techrepublic.com/article/how-to-install-best-system-monitors-for-linux-desktop/). 

I am immediately sold. Thank you very much for this wonderful utility. Before I shelve the Gnome System Monitor for good. I hope you would consider to add the File System view:

![Gnome_SystemMonitor_FileSystem](https://user-images.githubusercontent.com/72353094/159102433-53f3f9db-8213-46b9-9a00-a0753aebabf0.png)

**Comment by hakandundar34coding** [comment]
There was ```Storage``` tab and I removed it in one of the previous versions. Because the application was too large in terms of lines of code. But a similar feature may be added for listing storage devices in the newer versions. A design change may be made for the ```Disk``` tab or customization menu of this tab in order to add this feature.

Here is a screenshot of the removed tab:

![storage_tab_dark_system_theme](https://user-images.githubusercontent.com/90193017/159109673-fadf1f0e-df5d-4962-b64a-ef599c73d939.png)

**Comment by Trikenstein** [comment]
Oh cool. The "Storage" screen you show is indeed completed. Personally, what I used in Gnome System Monitor, File System is a quick glance on the disks and how full they are. As for the features you show (Browse, Mount, Unmount, Remove, Copy) I would probably never use. Either because it is a rare operation or there are different way (like using the File manager to browse or unmount USB drive)

**Comment by hakandundar34coding** [comment]
It has been a long time since the last comment. But disk list and disk usage information are shown in the unified tab and device selector (v1.15.0).

More details can be seen on the Disk tab after selecting a disk.

Here is an example screenshot:
![smc_disk_list](https://user-images.githubusercontent.com/90193017/168006817-b4735cc5-85e5-46d5-a192-15aa664f123d.png)
