### ISSUE TITLE
How to run when installed into /usr/local/?

### ISSUE THREAD

**Issue by paxe** [hakandundar34coding/system-monitoring-center#38]
I'm using your code as currently in the git repo, and have hacked setup.py to install into /usr/local/...
Is there some confusion now then between /usr/lib/python3 and /usr/local/lib/python3.9?
Here's what I get:

Traceback (most recent call last):
  File "/usr/local/bin/system-monitoring-center", line 4, in <module>
    __import__('pkg_resources').run_script('System-Monitoring-Center==1.6.0', 'system-monitoring-center')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/System_Monitoring_Center-1.6.0-py3.9.egg/EGG-INFO/scripts/system-monitoring-center", line 5, in <module>
ModuleNotFoundError: No module named 'Main'

**Comment by hakandundar34coding** [comment]
The only installation directory is ```/usr/share/system-monitoring-center```. I have not used another directory for installing the application. The application is not designed as a Python package.

- The application is run by using the shortcut in the start menu or terminal.
- The starter file (```system-monitoring-center```) is run in the ```/bin``` directory.
- It is a Python file and changes the directory to ```/usr/share/system-monitoring-center/src/```.
- It imports ```Main.py``` module which is in ```/usr/share/system-monitoring-center/src/```.

There may be a problem for changing the directory for importing the ```Main``` module.

I do not know that why you changed the installation directory but did you edited ```system-monitoring-center``` file for the new installation directory?

**Comment by paxe** [comment]
Do you mean edit integration/system-monitoring-center or build/scripts-3.9/system-monitoring-center? I tried both, and that does get the program to start properly.

I only want it in /usr/local/ because it is better practice to have rest of /usr/ handled by package management.

Have you hosted a .deb package in an apt repository anywhere? I also don't like doing a one-time install of a package without having any upgrade process in mind.

Anyway, thanks for your answers.

**Comment by hakandundar34coding** [comment]
It was ```integration/system-monitoring-center``` and it looks like the ```ModuleNotFoundError``` problem is solved.

About the package repositories:

Currently System Monitoring Center is in these repositories:
* For .deb packages:
    Pardus GNU/Linux repository. This is a Debian based distribution.
* For pacman packages:
    AUR repository.

The application may be added into more repositories if package maintainers recognize the application and add it.

Also an another user wanted PPA repository for the application in this [issue](https://github.com/hakandundar34coding/system-monitoring-center/issues/36). But there are too many packaging types/repositories/distributions to maintain.

There is a different packaging type: Flatpak. But as far as I know an application in flatpak can not access to all of the processes of the system because of the sandbox system. Some main functions of the application will not work in this situation.

**Comment by paxe** [comment]
Thanks again for your answers, I'll close this now.
