### ISSUE TITLE
[Feature Request] Have tree cpu and memory usage columns at Processes tab for better sorting

### ISSUE THREAD

**Issue by HelgeBoehme** [hakandundar34coding/system-monitoring-center#50]
Sorting processes by CPU or Memory (maybe more) is currently not meaningful if processes are shown as tree, because higher tree nodes have precedence. This is even worse if tree nodes are collapsed, then you cannot see or find processes with high usage.

Possible solutions (for tree mode only):

- have additional columns like Tree CPU, Tree Memory etc. which sum up the values of all child tree nodes
- do not have additional columns, but change sort behavior of current columns to use the tree sum instead of single node value

**Comment by hakandundar34coding** [comment]
Gnome System Monitor and XFCE4 Task Manager also have similar behavior.

For sorting, default sorting feature of the GTK3 is used in code of this application.

Adding this feature would increase CPU usage on the Processes tab. Because searching parent of every process and summation of CPU/RAM usages is not a simple function. For example, adding a new column (as a new feature) such as "start time of processes" is easier and impact on CPU consumption is relatively lower when compared to this feature.

This detailed feature would be added if this application is written in C++/Rust. Performance of Python for several cases is lower when compared to these programming languages.

I will close this issue but you can writte additional comments.
