### ISSUE TITLE
No option to change the app language

### ISSUE THREAD

**Issue by K0-RR** [hakandundar34coding/system-monitoring-center#54]

**Comment by hakandundar34coding** [comment]
It gives error if the selected locale is not installed on the system even if there are additional translation files in the locale folder. In most cases, changing the language between system language and English (default language of the application GUI) will work. In other words, there will be two options: English and System if the user does not install additional languages to the system. Do you want this option?

Features that are not very important are not added to the application. Because number of translation text also increases.
Some features of the application was removed for maintenance reasons and number of translation text.

Currently, system language is automatically selected. If there are translations for your language and if you want to use English GUI, you can delete/move translation file in the ```.../systemmonitoringcenter/locale/``` folder.

**Comment by hakandundar34coding** [comment]
Currently, system language is automatically selected. If there are translations for your language and if you want to use English GUI, you can delete/move translation file in the .../systemmonitoringcenter/locale/ folder.

This feature may be added in the newer versions.
