### ISSUE TITLE
Refresh rate: [Unknown]

### ISSUE THREAD

**Issue by K0-RR** [hakandundar34coding/system-monitoring-center#55]
![image](https://user-images.githubusercontent.com/43277609/161448790-3630a423-682d-4cbe-b200-cc7565fa4fca.png)

**Comment by hakandundar34coding** [comment]
GTK features are used for getting refresh rate and GTK does not support getting this information on systems with Wayland windowing system. It may be fixed in GTK4 but GTK is not in repositories of some distributions.

Several versions ago, ```xrandr``` command was used for getting this information and as far as I know there was no problem. But GTK is used instead of xrandr for lower CPU usage.

The bug is fixed for systems with single monitor and source code is updated. ```xrandr``` is used if refresh rate is not get. But installation of ```xrandr``` may be required for your system. It is already installed on some systems.
