### ISSUE TITLE
Some dependency issues on from AUR

### ISSUE THREAD

**Issue by NickMatthews-1** [hakandundar34coding/system-monitoring-center#64]
I would like to thank you for the wonderful piece of software you have created here. It is very polished and works amazingly well.

Now, onto what I found.

When trying to download from the AUR in Manjaro it kept chucking an error for python-tomli 2.0.1-1. This is down to the fact that the repository cannot be found to download the required package. I understand that this is an issue you have no control over so I am more then happy to chalk it up to a non issue. 

When installing via pip instead it works perfectly fine on Manjaro. No bothers at all.

I have also made a video about this that will be published tomorrow. Again, thank you for the software and I hope you enjoy the video. Have a good day!

https://youtu.be/4YIqaUx63Lg

**Comment by hakandundar34coding** [comment]
Hello @Nmatt1,
I have not watched the video yet. It is hidden now. I will watch it when it is available. :)

About the package problem:
I use a debian-based distribution. I use Arch Linux based distributions for testing on virtual machines. I do not know a lot of details about packaging on Arch Linux.

Hello @yochananmarqos,
There is a problem with `python-tomli` package during installation of the application from AUR. What can be done to fix this problem?

**Comment by yochananmarqos** [comment]
@Nmatt1 Please post a log, not a video. Your video is private, by the way.

**Comment by NickMatthews-1** [comment]
Hi there. I can get the log in a short while. The video will be live at 12:00 EST today. It came back as a 404 error. I will have the logs soon.

**Comment by NickMatthews-1** [comment]
![Untitled](https://user-images.githubusercontent.com/25136516/164913099-7e175c4d-c47b-433d-b533-c3a611a1e9c4.png)
Here is the logs that you may need!

**Comment by yochananmarqos** [comment]
Your mirrors are out of date, see the [Manjaro Wiki](https://wiki.manjaro.org/index.php/Pacman-mirrors#Update_mirrorlist_with_the_fastest_mirrors).

**Comment by hakandundar34coding** [comment]
@Nmatt1
I watched the video. You can restart the system if GUI images are not shown. Cache for these images are not updated immediately on some systems. I have updated the explanations in the README file (in home page of the project).

Do not use Python package version and system package version at the same time. If you want to use the other version, remove the existing one and install the other.

About the GPU tab:
GPU tab is redesigned and FPS counter is removed. GPU load, frequency, temperature, memory, etc. is shown. There is a bug for AMD GPUs and it will be fixed today. You can find an example screenshot of the new GPU tab on the home page of the project.

About the Startup tab:
There are a lot of desktop environments. Different DEs use different startup values. This is very complicated. Instead of showing check marks (enabled/disabled) files are listed. Content of these affect startup behavior of the application.

About the CPU tab:
Selecting CPU core affects CPU frequency, cache memory values etc. Most of the CPU cores are same. But there are some new CPUs which have cores with different features.

General:
The application supports PolicyKit. It asks user password if a service is tried to be masked, a process of other user is tried to be ended, etc.

**Comment by NickMatthews-1** [comment]
Thank you very much for the clarification. I will do an update video to this in the future. I very much believe that this is a very handy and good piece of software.

Id be more then happy to work with you in the future about making another video on it.

If you like to contact me you can do so via email, at: nick@linuxpanic.com

Thank you for your time and I look forward to hearing from you in the future.

**Comment by hakandundar34coding** [comment]
Is the dependency problem solved?

**Comment by NickMatthews-1** [comment]
The updating fixed the issues. But I will attempt on my personal Manjaro install later on today and test it to confirm working.

**Comment by hakandundar34coding** [comment]
@yochananmarqos
You can remove `libwnck3` dependency. It was removed from deb package dependency list several versions ago.

**Comment by yochananmarqos** [comment]
@hakandundar34coding Done.

**Comment by hakandundar34coding** [comment]
@yochananmarqos
You are very fast to solve the problems and respond.

**Comment by hakandundar34coding** [comment]
@Nmatt1
Latest version (v1.12.1) is published.

**Comment by hakandundar34coding** [comment]
@Nmatt1
Is the problem fixed?

@yochananmarqos
On some Arch Linux systems it does not ask for password by using polkit even if it is installed. `pkexec` command is used for opening password dialog. Is this a dependency problem?

**Comment by yochananmarqos** [comment]
One cannot just run anything with `pkexec`. I've now included a [policy file](https://aur.archlinux.org/cgit/aur.git/tree/org.freedesktop.system-monitoring-center.policy?h=system-monitoring-center).

**Comment by hakandundar34coding** [comment]
@Nmatt1
I will close this issue. You can write if there is a problem with the dependencies.
