### ISSUE TITLE
Please add graphing for sensors

### ISSUE THREAD

**Issue by gnarlin** [hakandundar34coding/system-monitoring-center#66]
Please consider adding graphs for the sensor outputs. For example: being able to watch a graph of cpu and gpu temperatures over time along with fan speeds, each in different (maybe even customizable) colours. Cpu, ram, gpu, network  and disks all output to graphs, so why not the temperatures and fan speeds?

**Comment by hakandundar34coding** [comment]
This feature requires monitoring sensors in the background. This would increase CPU consumption and increase start speed of the application slightly. Because it requires reading several sensor files repeatedly. This application is written in Python language and it is slower in several cases when compared to C++ or Rust. Both Python and tracking sensor files in the background increase CPU usage. Probably this feature will not be added.
