### ISSUE TITLE
Can't delete System-wide startup files with root privileges 

### ISSUE THREAD

**Issue by awohsen** [hakandundar34coding/system-monitoring-center#68]
![image](https://user-images.githubusercontent.com/93778317/164914128-b47d43f2-64e3-4977-a244-03e41ed70eca.png)

**Comment by hakandundar34coding** [comment]
`Delete` feature is disabled for system-wide startup items intentionally. Deleted file can not be recovered and some system functions/applications may not work properly.

**Comment by awohsen** [comment]
So if it's about recovery, I guess there should be an option for disable instead of delete in both system-wide(with privileges) or user-specific items, just like a windows task manager.

**Comment by hakandundar34coding** [comment]
There are a lot of desktop environments. Different DEs use different startup values. This is very complicated. Instead of showing check marks (enabled/disabled) files are listed. Content of these affect startup behavior of the application.

Here is a screenshot of the Startup tab in one of the old versions:
![smc_startup_old](https://user-images.githubusercontent.com/90193017/164959621-ce3c29fe-8a55-4776-b6b3-bdb53ff27b65.png)

**Comment by hakandundar34coding** [comment]
You can try these steps if you want to disable a startup item:
- Add a new item with the same name (see the file name from `Browse '.desktop' File...`.
- Open this new file.
- Add this line and save: `Hidden=true`

**Comment by awohsen** [comment]
ok, thanks. so it's hard to maintain and achieve that feature for now. 

btw whenever you want close this issue if it's considered solved

**Comment by hakandundar34coding** [comment]
Also there are other values in the .desktop files for startup behavior:
OnlyShowIn, NotShowIn, Hidden, NoDisplay. One setting may override the others. It becames more complicated if there are more than one DEs installed on the same system.

Startup module was one of the most complicated parts of the application. It is simplified for easier maintenance.
