### ISSUE TITLE
Update: Polish translation

### ISSUE THREAD

**Issue by ski007** [hakandundar34coding/system-monitoring-center#75]
I updated the Polish translation a bit but I don't know how to add it to the program. I do not know if it will work well with the program and displayed windows.
I haven't polished everything yet, but if it's OK ... then I'll improve even further when I find some time
https://github.com/ski007/system-monitoring-center/blob/master/locale/pl/system-monitoring-center.po

**Comment by hakandundar34coding** [comment]
You can send a pull request for adding it to the latest source code.

You can use Poedit program to edit `.po` file and generate a `.mo` file. `.mo` file is generated automatically after Save button is clicked. The applciation uses `.mo` file for translations.

Also you can send a pull request only for `.po` file if you edited the `.po` file manually. I can generate a `.mo` file.

**Comment by hakandundar34coding** [comment]
Can you follow these [steps](https://github.com/hakandundar34coding/system-monitoring-center/pull/76#issuecomment-1119634082)?

**Comment by hakandundar34coding** [comment]
There were conflicts because project structure (folders) changed after you generated a branch. It is changed and pull request is merged.

There are some new texts for translation after this change. Also some problematic translations are shown with orange color when translation file is opened with Poedit.

You can generate a new fork if you want to translate the new texts.

Here is a screenshot of the Poedit application (and some of the problematic translations):
![smc_translation](https://user-images.githubusercontent.com/90193017/167174667-db2e12dc-6b70-49b2-ad2d-23a3329b2d06.png)

**Comment by ski007** [comment]
I opened the .po file with an editor and checked by clicking the option: verify
a window appeared with the information that everything is OK?
only 8 items still require translation...
![Zrzut ekranu z 2022-05-06 18-58-26](https://user-images.githubusercontent.com/50265514/167178503-d23131a3-e225-4b33-8ae9-29a30cfd7d7c.png)
[system-monitoring-center.po.zip](https://github.com/hakandundar34coding/system-monitoring-center/files/8642341/system-monitoring-center.po.zip)

**Comment by hakandundar34coding** [comment]
Poedit shows information for 23 text which are not translated. You can sort the texts by translation by changing the options in the view menu.

Your .po file may be old. If you have time, you can download the latest source [code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) or you can generate a new fork for the latest file. Also another contributor may update the translation.
