### ISSUE TITLE
System disk information is not correct (Disk Details window)

### ISSUE THREAD

**Issue by ski007** [hakandundar34coding/system-monitoring-center#77]
I know this is not information from the program itself
system-monitoring-center but is it worth asking if this is a bug?
On the main page you can read that dyst sda3 is a system disk and in the detailed information that it is not?
![Zrzut ekranu z 2022-05-07 12-32-33](https://user-images.githubusercontent.com/50265514/167250927-ed3764c5-8e5b-43b2-87ad-7c66d1377223.png)

**Comment by hakandundar34coding** [comment]
This bug will be fixed in the next version of the application (about less than a week).

**Comment by ski007** [comment]
there may be duplicate disk read speed entries in the process details...
![Zrzut ekranu z 2022-05-11 17-57-39](https://user-images.githubusercontent.com/50265514/167895951-23d58ef7-125e-47f5-bc5d-8831a29114d5.png)

**Comment by hakandundar34coding** [comment]
- System disk information bug on Disk Details window is fixed.
- Disk Write Speed text problem was fixed during code/GUI updates a few days ago.
- Latest translation file for Polish language is used by the updated code.

You can install latest version (v1.15.0) of the application in order to use the updated code.
There are some GUI changes/simplifications and some of the [translations](https://github.com/hakandundar34coding/system-monitoring-center/issues/75) are not usable now.

- RAM is translated as two words in your language and RAM usage chart looks very long. Is the translation RAM or Pamięć RAM?
- Physical RAM is translated as Pamięć RAM. I do not know your language. But is it correct?

Physical RAM and RAM capacity are different values. RAM capacity may be shown as 11.6 GiB even if there is 12 GiB physical RAM on your system.
