### ISSUE TITLE
L1d and L1i are backwards compared to lscpu

### ISSUE THREAD

**Issue by theofficialgman** [hakandundar34coding/system-monitoring-center#82]
![Screenshot from 2022-05-22 19-11-39](https://user-images.githubusercontent.com/28281419/169720107-15e05313-206f-4629-ac09-dc14c01f9b79.png)
 you appear to have misordered it here: https://github.com/hakandundar34coding/system-monitoring-center/blob/1222e472016774b0eb5e2ea9991c7cade50eb90f/src/Cpu.py#L121

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated.

I have never seen a CPU with different L1d and L1i caches for the same core before. Is it a Nvidia (ARM) CPU?

Additional information: System Monitoring Center shows cache memories for the selected core. On x86_64 systems `lscpu` shows total cache memories. For example: for a 4-core (physical) CPU, System Monitoring Center shows 256K as L2 cache memory and lscpu shows 1MiB (total L2 cache).

But the values are same for System Monitoring Center and lspcu on your system. L1 and L2 cache memories are for each core. Is behavior of lscpu on your system different?

**Comment by theofficialgman** [comment]
> I have never seen a CPU with different L1d and L1i caches for the same core before. Is it a Nvidia (ARM) CPU?

yes this is the switch (tegra X1).

> But the values are same for System Monitoring Center and lspcu on your system. L1 and L2 cache memories are for each core. Is behavior of lscpu on your system different?

lscpu is different on arm (or at least older lscpu)
```
lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               1
Model name:          Cortex-A57
Stepping:            r1p1
CPU max MHz:         2091.0000
CPU min MHz:         102.0000
BogoMIPS:            38.40
L1d cache:           32K
L1i cache:           48K
L2 cache:            2048K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```

edit: sorry didn't mean to post immediatly


as per nvidia, the L2 is shared (so there is only one) and the L1 d/i are per core values
```
The Cortex A57 CPU complex on Tegra X1 shares a
common 2MB L2 cache, and each of the four CPU cores has a 48KB L1 instruction cache and a 32KB L1
data cache.
```

**Comment by hakandundar34coding** [comment]
Interesting information about different hardware.

The bug was fixed. There will be a package (v1.17.0) with the updated code in this week. I will close this issue.
