### ISSUE TITLE
Missing support for Gnome 40+ bright/dark theme

### ISSUE THREAD

**Issue by theCalcaholic** [hakandundar34coding/system-monitoring-center#94]
With the move to Gnome 40+ (42 in my case), System Monitoring Center stopped honoring the system theme settings.

Here is a screenshot while using Gnome dark theme:

![Screenshot from 2022-06-22 11-17-07](https://user-images.githubusercontent.com/6317548/174992594-7c4e5981-e5c5-422b-8b14-c3098c5f68f0.png)

SMC was installed via `pip install --user system-monitoring-center`

**Comment by hakandundar34coding** [comment]
Does other `GTK3` applications adapt to dark theme on your system?

**Comment by hakandundar34coding** [comment]
I have tested the application on virtual machine. Some newer distributions use Gnome 42 desktop environment and there are some changes for theme settings. GTK4 applications can adapt to theme setting changes but GTK3 applications may require some code changes for dark theme changes.

There will be code changes for System Monitoring Center for supporting dark theme on these systems.

There are some suggestions on the web for dark theme support of GTK3 applications. There is one of them:

- Installing gnome-tweaks application, opening Appearance page and selecting dark theme option for Legacy Aplications field.

There are also another suggestions which require using some extensions.

**Comment by theCalcaholic** [comment]
The workaround using Gnome Tweaks worked flawlessly.

Thanks for your work! You are providing the best system monitoring GUI for end users on Linux

**Comment by hakandundar34coding** [comment]
This fix will be included in a version later than v1.21.0. Because this version of the application is packaged and it will be downloadable tomorrow.

**Comment by hakandundar34coding** [comment]
The bug is fixed. The application have to be reopened after changing the system theme (light/dark). Using `gnome-tweaks` is your decision. I do not know if it has other effects.

You can follow these steps if you want to test it.

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Check if dark theme is used.
- Also check the terminal window to see if there are errors.

There will be a new package (v1.22.0) this week and it will include the latest source code.

**Comment by hakandundar34coding** [comment]
The package (v1.22.0) can be installed. It contains the latest source code.

I will close this issue.
