### ISSUE TITLE
Feature request: network usage per process

### ISSUE THREAD

**Issue by Breigner01** [hakandundar34coding/system-monitoring-center#99]
All the column available in the processes tab are really nice.

I would love to see 2 more columns added to show network usage of each process.
We could see download and upload speed of each process.

Other process monitoring tools like the one from KDE does it so I believe it should be doable.

**Comment by The-Real-Admin-Guy** [comment]
First let me say this:  Amazing work, well done, useful and highly detailed functionality!

Any Plans to allow for remote monitoring of devices?

 I love this thing and would like to use it to monitor remote server instances...  
Remote task management would also be useful...

**Comment by hakandundar34coding** [comment]
It has been a long time after this issue is opened. A few methods have been found for adding this feature. As far as I know they require root privileges for getting download/upload speeds per-process.

This feature may be added if a method without root privilege requirement is found. I will close this issue. But you can write comments.
